name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  nosetests:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t", "pypy-3.11"]
        exclude:
          - os: windows-latest
            python-version: "pypy-3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: python3 -m pip install --upgrade pip
      - run: pip install nose-py3 pytest pytest-asyncio
      - run: pip install --editable .
      - run: nosetests
      - run: pytest || true
